table order_detail_sr
	lineageTag: 2141bbdb-ffd7-49a5-a37a-8be4f7a8ac6f

	measure Actual_Ach_% = if([Budget Orders $_sr]  = 0,1, divide([Actual_sr], [Budget Orders $_sr]))
		lineageTag: 072bbe95-c48c-48c9-971b-3d56ed752ad2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget Orders $_sr' = ```
			if(isblank(sum(Budget[Orders_Sales])),0,sum(Budget[Orders_Sales]) ) 
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 10315bf3-2293-4c84-af31-a218cd014f31

	measure Actual_sr = if(isblank(sum(order_detail_sr[raw_actual])),0,sum(order_detail_sr[raw_actual]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5feb4f79-dc54-4557-88e9-3be36b8a65ad

	measure Bottles_Ach_% = if([Budget Orders Units_sr]  = 0,1, divide([Qty_sr], [Budget Orders Units_sr]))
		lineageTag: 9f210cbc-9df6-4529-bbaa-9cd10d1a690d

	measure 'Budget Orders KG_sr' = ```
			if(isblank(sum(Budget[Orders_KG])),0,sum(Budget[Orders_KG]) ) 
			```
		lineageTag: 8c641d54-e212-4f99-9899-89530e235489

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget Orders Units_sr' = ```
			if(isblank(sum(Budget[Orders_Bottles])),0,sum(Budget[Orders_Bottles]) ) 
			```
		formatString: #,0.00
		lineageTag: b5a9f211-18f5-4545-bb57-32184e889e3a

	measure 'Budget Orders VCM_sr' = ```
			if(isblank(sum(Budget[Orders_VC_Margin])),0,sum(Budget[Orders_VC_Margin]) ) 
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 28a2e60d-0868-4ca4-ba3f-da1bbfdafbdb

	measure Qty_sr = if(isblank(sum(order_detail_sr[raw_qty])),0,sum(order_detail_sr[raw_qty]))
		lineageTag: 42e2acb0-4a0a-45c0-9c7e-54fd254e34b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure QVC_sr = if(isblank(sum(order_detail_sr[raw_qvc])),0,sum(order_detail_sr[raw_qvc]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 89f2efa6-f874-4667-b8ab-28b76b35696f

	measure 'CM (%) Actuals_sr' = ```
			divide([QVC_sr],[Actual_sr],0) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a76ca910-69de-4de0-baeb-0404b46d1cf3

	measure 'F (U) $_sr' = [Actual_sr] - [Budget Orders $_sr]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b881fef0-cca5-417d-9758-7c4f8b57627b

	measure 'F (U) Bottles_sr' = [Qty_sr] - [Budget Orders Units_sr]
		lineageTag: 9752dc53-9b75-4c3a-b24f-82e376cf7872

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'F (U) QVC_sr' = [QVC_sr] - [Budget Orders VCM_sr]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5a11bdda-57ed-4a51-b3ea-4584c51fd34c

	measure 'Forecast Value' = ```
			if(isblank(sum(Monthly_Forecasts[forecast])),0,sum(Monthly_Forecasts[forecast])) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8de486d2-7f37-4db6-a9a1-f8ecba7a82b0

	measure Remaining_sr = if([Forecast_sr] = 0,0,[Forecast_sr] - [Actual_sr])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3426e65e-7553-48b5-a168-05938bd3a069

	measure Units_Ach_% = if([Budget Orders Units_sr]  = 0,1, divide([Qty_sr], [Budget Orders Units_sr]))
		lineageTag: 18adbfda-0ead-46ae-9f29-6f1cf187a95d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Flag_Budget_MTD =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([Actual_sr]) && [Actual_sr] = 0 && [Forecast Value]  = 0, BLANK(),
			    [Budget Orders $] = 0 && [Actual_sr] = 0 && [Forecast Value]  = 0 , BLANK(),
			    1
			)
		formatString: 0
		lineageTag: 50beaf68-bf36-4d68-a1f3-6e2d3e371043

	measure QVC_Ach_% = if([Budget Orders VCM_sr]  = 0,1, divide([QVC_sr], [Budget Orders VCM_sr]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 120a254c-a9ce-460c-9468-b43a9f13e13a

	measure Orders($)_sr = divide([F (U) $_sr],[Budget Orders $],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 62c4c7c1-bdd7-4a26-85ec-1b161def0c71

	measure VOL(Units) = DIVIDE([F (U) Bottles_sr],[Budget Orders Units_sr],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0bcf5e4-1a9f-4e7c-a3c4-9d72514090d0

	measure CM($)_sr = DIVIDE([F (U) QVC_sr],[Budget Orders VCM_sr],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 64ad375f-d39c-4107-a4f3-9bab101bddc1

	measure 'CM (%) Budget_sr' = divide([Budget Orders VCM_sr],[Budget Orders $_sr],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f5d1471c-ad34-44be-b5ea-541d7c49a8cb

	measure 'CM (%) Variance_sr' = ```
			[CM (%) Actuals_sr] - [CM (%) Budget_sr] 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b4ad5288-09e2-4e78-8825-92a3c368b7bc

	measure Flag_Budget =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([Actual_sr]) && [Actual_sr] = 0, BLANK(),
			    [Budget Orders $] = 0 && [Actual_sr] = 0 , BLANK(),
			    1
			)
		formatString: 0
		lineageTag: d9061925-cb9b-4c91-92bc-f2cd15650fd1

	column bi_id
		dataType: int64
		formatString: 0
		lineageTag: eddcd755-e712-4a37-8187-21c47d7b44e8
		summarizeBy: none
		sourceColumn: bi_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 65389f60-a6a0-4972-a4a0-b28123770e90
		summarizeBy: none
		sourceColumn: date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column to_orddate
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f401e41-75ba-4a0b-88db-ee2991e1bf0f
		summarizeBy: none
		sourceColumn: to_orddate

		variation Variation
			isDefault
			relationship: 12b11be0-9423-49c2-bb96-2282154e40e7
			defaultHierarchy: LocalDateTable_0088e3fa-6b31-4fa6-bf20-864ce96aa772.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column to_ordnum
		dataType: double
		lineageTag: 97a6dec6-f23f-4fa5-babd-df807882f4a8
		summarizeBy: sum
		sourceColumn: to_ordnum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Description
		dataType: string
		lineageTag: 2aa149d6-b0d2-4c97-aa86-80eba2532031
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Part_Number
		dataType: string
		lineageTag: aef4b597-2bdf-49db-b979-f65d8a9c82ce
		summarizeBy: none
		sourceColumn: Part_Number

		annotation SummarizationSetBy = Automatic

	column order_type
		dataType: string
		lineageTag: 6b6e2a65-8592-4116-b929-2fc2fd9098a7
		summarizeBy: none
		sourceColumn: order_type

		annotation SummarizationSetBy = Automatic

	column username
		dataType: string
		lineageTag: 4d361ba6-b6a5-476f-a7fe-5a83bfb04d03
		summarizeBy: none
		sourceColumn: username

		annotation SummarizationSetBy = Automatic

	column raw_actual
		dataType: double
		lineageTag: bf538f4f-0ada-46f7-9d67-caa5562c69b1
		summarizeBy: sum
		sourceColumn: raw_actual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_qty
		dataType: double
		lineageTag: 4cbe70ed-3dd5-45c5-99a4-fb0893d44d35
		summarizeBy: sum
		sourceColumn: raw_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_qvc
		dataType: double
		lineageTag: 4fbbbd93-9615-4857-b3bf-b8f9f4d4088d
		summarizeBy: sum
		sourceColumn: raw_qvc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_kg
		dataType: double
		lineageTag: c19d8e0f-16f2-4a27-99dd-efe2ccb2b579
		summarizeBy: sum
		sourceColumn: raw_kg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column forecast
		dataType: double
		lineageTag: e9da2276-a50a-42ba-ab8b-8d0ebe573e45
		summarizeBy: sum
		sourceColumn: forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flag
		dataType: int64
		formatString: 0
		lineageTag: 0de8c7a0-a48f-477a-b1e6-b000a85a3f05
		summarizeBy: sum
		sourceColumn: flag

		annotation SummarizationSetBy = Automatic

	column monthly_forecast
		dataType: double
		lineageTag: 5898ee06-0964-4e64-9fe0-2a2c1195f191
		summarizeBy: sum
		sourceColumn: monthly_forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition order_detail_sr = m
		mode: import
		source =
				let
				    Source = Sql.Databases("CATSQL1\CATSQL1"),
				    deacom_replica = Source{[Name="deacom_replica"]}[Data],
				    dbo_order_detail_sr = deacom_replica{[Schema="dbo",Item="order_detail_sr"]}[Data]
				in
				    dbo_order_detail_sr

	annotation PBI_ResultType = Table

